Add support for publicKey from BEP46
webtorrent/magnet-uri pull request #35
Opened 2020-05-11 20:58 UTC by RangerMauve

**What is the purpose of this pull request? (put an "X" next to item)**

[ ] Documentation update
[ ] Bug fix
[x] New feature
[ ] Other, please explain:

**What changes did you make? (Give an overview)**

- Added encode/decode rules for `xs=urn:btpk:PUBLIC_KEY` to parse out a `publicKey` based on [BEP 46](http://bittorrent.org/beps/bep_0046.html)
- Encoding got modified to only use URI encode for `xs` strings that don't start with `urn:btpk:`

**Which issue (if any) does this pull request address?**

**Is there anything you'd like reviewers to focus on?**

2020-11-12 19:37 UTC, RangerMauve commented
@alxhotel Is there anything else I can do to get this merged in? 😅

2020-11-13 03:58 UTC, feross requested changes
LGTM! This is basically ready to merge, except two nits I mentioned inline.

2020-11-13 03:58 UTC, feross commented on index.js
> +        result.publicKey = m[1]
This is a hex string, right? Why no `.toLowerCase()` like we did for `xt` above?

2020-11-13 03:58 UTC, feross commented on index.js
> +        if (key === 'xs' && !val.startsWith('urn:btpk')) {
Can you change this to `startsWith('urn:btpk:')` (note the trailing colon!)

2020-11-13 03:59 UTC, feross commented
@RangerMauve Yep, see the inline comments! @alxhotel Thanks for updating this PR, and bringing attention back to it

2020-11-13 19:26 UTC, RangerMauve commented
@feross Thank you for the review! Just added the changes you mentioned. 😁

2020-11-14 00:51 UTC, feross approved these changes
LGTM

2020-11-14 00:51 UTC, merged

2020-11-14 00:52 UTC, feross commented
Released as 6.1.0

2020-11-14 19:02 UTC, RangerMauve commented
Sweet. Thank you for merging this in! I'm excited to get the public key stuff working in higher levels of the stack, too. 😁